name: Release v1.0.7

on:
  push:
    branches: [ master ]
    paths: [ '.github/workflows/release-v1.0.7.yml' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    env:
      VERSION: v1.0.7
      RELEASE_VERSION: v1.0.7
      MAVEN_PUBLISHING_URL: https://nexus.gtnewhorizons.com/repository/releases/
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 32

      - name: Determine JDK versions
        id: list-jdk-versions
        shell: bash
        run: |
          (
            echo 'java-versions<<EOF'
            echo 8
            echo 17
            echo 21
            if [[ -f gradle/gradle-daemon-jvm.properties ]]; then
              yq -pprops -oprops '.toolchainVersion' gradle/gradle-daemon-jvm.properties
            fi
            echo EOF
          ) | tee -a "${GITHUB_OUTPUT}"

      - name: Set up JDK versions
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.list-jdk-versions.outputs.java-versions }}
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          validate-wrappers: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup the workspace
        run: ./gradlew --build-cache --info --stacktrace -PmavenPublishUrl='${{ env.MAVEN_PUBLISHING_URL }}' setupCIWorkspace

      - name: Build the mod
        run: ./gradlew --build-cache --info --stacktrace -PmavenPublishUrl='${{ env.MAVEN_PUBLISHING_URL }}' assemble

      - name: Publish GitHub release
        run: gh release create "${RELEASE_VERSION}" --target "${GITHUB_SHA}" --generate-notes ./build/libs/*.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
